apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap
  namespace: logging
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0"
    elasticsearch.hosts: ["http://elasticsearch:9200"]
    monitoring.ui.container.elasticsearch.enabled: true
    elasticsearch.ssl.verificationMode: none
    status.allowAnonymous: true
    xpack.encryptedSavedObjects.encryptionKey: "gHZ7wuHTkZOHlnN1yQ3nTLvZP+yzJbbjXoPC1vBGhMo="