apiVersion: v1
kind: Service
metadata:
  name: icinga-service
  namespace: inciga
spec:
  type: NodePort
  selector:
    app: icinga
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 # NodePort range is typically 30000-32767
