apiVersion: apps/v1
kind: Deployment
metadata:
  name: icinga-deployment
  namespace: inciga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icinga
  template:
    metadata:
      labels:
        app: icinga
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
      - name: icinga
        image: icinga/icinga2
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/var/lib/icinga2"
          name: icinga-storage
          subPath: var/lib/icinga2
        - mountPath: "/etc/icinga2"
          name: icinga-storage
          subPath: etc/icinga2
      volumes:
      - name: icinga-storage
        persistentVolumeClaim:
          claimName: pvc-icinga
