apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: kubeconfig-volume
          mountPath: /var/jenkins_kubeconfig
          readOnly: true
      volumes:
      - name: jenkins-home
        emptyDir: {}
      - name: kubeconfig-volume
        secret:
          secretName: jenkins-kubeconfig
