apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"jenkins","namespace":"jenkins"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"jenkins"}},"template":{"metadata":{"labels":{"app":"jenkins"}},"spec":{"containers":[{"image":"jenkins/jenkins:lts","name":"jenkins","ports":[{"containerPort":8080}],"volumeMounts":[{"mountPath":"/var/jenkins_home","name":"jenkins-home"},{"mountPath":"/var/jenkins_kubeconfig","name":"kubeconfig-volume","readOnly":true}]}],"volumes":[{"emptyDir":{},"name":"jenkins-home"},{"name":"kubeconfig-volume","secret":{"secretName":"jenkins-kubeconfig"}}]}}}}
  creationTimestamp: "2024-03-29T11:34:22Z"
  generation: 3
  name: jenkins
  namespace: jenkins
  resourceVersion: "237036"
  uid: 05fb144b-4da7-4640-8f15-b4ba4771e4bd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jenkins
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins
    spec:
      containers:
      - image: jenkins/jenkins:lts
        imagePullPolicy: IfNotPresent
        name: jenkins
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        - mountPath: /var/jenkins_kubeconfig
          name: kubeconfig-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: jenkins-sa
      serviceAccountName: jenkins-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: jenkins-home
      - name: kubeconfig-volume
        secret:
          defaultMode: 420
          secretName: jenkins-kubeconfig
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-03-29T11:42:42Z"
    lastUpdateTime: "2024-03-29T11:42:42Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-03-29T11:34:22Z"
    lastUpdateTime: "2024-04-03T04:57:04Z"
    message: ReplicaSet "jenkins-64df8ff6dc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
