apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: ns3
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Specify a version if needed, e.g., nginx:1.19.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80  # Assuming default Nginx port, adjust if your Nginx listens on a different port
        resources: {}  # Define limits and requests for resources as necessary
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
