apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-icinga
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-icinga
  namespace: inciga
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
